/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    countries: Country;
    cities: City;
    'guide-sections': GuideSection;
    'guide-items': GuideItem;
    districts: District;
    neighborhoods: Neighborhood;
    listings: Listing;
    itineraries: Itinerary;
    'ai-jobs': AiJob;
    'update-logs': UpdateLog;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    'guide-sections': GuideSectionsSelect<false> | GuideSectionsSelect<true>;
    'guide-items': GuideItemsSelect<false> | GuideItemsSelect<true>;
    districts: DistrictsSelect<false> | DistrictsSelect<true>;
    neighborhoods: NeighborhoodsSelect<false> | NeighborhoodsSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    itineraries: ItinerariesSelect<false> | ItinerariesSelect<true>;
    'ai-jobs': AiJobsSelect<false> | AiJobsSelect<true>;
    'update-logs': UpdateLogsSelect<false> | UpdateLogsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar' | 'ur') | ('en' | 'ar' | 'ur')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ar' | 'ur';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'registered-traveler' | 'business-owner' | 'editor' | 'seo-manager' | 'moderator' | 'admin' | 'super-admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  attribution?: string | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  slug: string;
  iso2: string;
  iso3: string;
  region: string;
  subregion?: string | null;
  capital?: string | null;
  currency: string;
  timezoneNotes?: string | null;
  languages?:
    | {
        language: string;
        id?: string | null;
      }[]
    | null;
  callingCodes?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  summary: string;
  flagEmoji?: string | null;
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'updated' | 'archived';
  seo: {
    title: string;
    description: string;
    canonicalUrl?: string | null;
    openGraphImage?: (number | null) | Media;
    robots: 'index,follow' | 'noindex,follow' | 'noindex,nofollow';
    schemaType: string;
  };
  sources?:
    | {
        label: string;
        url: string;
        type: 'official' | 'map-provider' | 'editorial' | 'partner' | 'user-submitted';
        verifiedAt: string;
        confidence: 'low' | 'medium' | 'high';
        id?: string | null;
      }[]
    | null;
  lastVerifiedAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  slug: string;
  country: number | Country;
  region?: string | null;
  locale: string;
  lede: string;
  heroImage?: (number | null) | Media;
  timezone: string;
  languages?:
    | {
        language: string;
        id?: string | null;
      }[]
    | null;
  currency: string;
  latitude: number;
  longitude: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  geo: [number, number];
  mapUrl: string;
  fastFacts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Mandatory 15-section Karachi-model city guide payload.
   */
  structuredSections:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'updated' | 'archived';
  seo: {
    title: string;
    description: string;
    canonicalUrl?: string | null;
    openGraphImage?: (number | null) | Media;
    robots: 'index,follow' | 'noindex,follow' | 'noindex,nofollow';
    schemaType: string;
  };
  sources?:
    | {
        label: string;
        url: string;
        type: 'official' | 'map-provider' | 'editorial' | 'partner' | 'user-submitted';
        verifiedAt: string;
        confidence: 'low' | 'medium' | 'high';
        id?: string | null;
      }[]
    | null;
  lastVerifiedAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-sections".
 */
export interface GuideSection {
  id: number;
  title: string;
  sectionSlug: string;
  city: number | City;
  sectionType: 'editorial' | 'directory' | 'mixed' | 'locator';
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sourceImport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'updated' | 'archived';
  seo: {
    title: string;
    description: string;
    canonicalUrl?: string | null;
    openGraphImage?: (number | null) | Media;
    robots: 'index,follow' | 'noindex,follow' | 'noindex,nofollow';
    schemaType: string;
  };
  sources?:
    | {
        label: string;
        url: string;
        type: 'official' | 'map-provider' | 'editorial' | 'partner' | 'user-submitted';
        verifiedAt: string;
        confidence: 'low' | 'medium' | 'high';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-items".
 */
export interface GuideItem {
  id: number;
  title: string;
  slug: string;
  kind: 'place' | 'hotel' | 'restaurant' | 'masjid' | 'shopping' | 'tour' | 'family' | 'festival';
  city: number | City;
  section?: (number | null) | GuideSection;
  sectionSlug: string;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  imageAlt: string;
  area?: string | null;
  category?: string | null;
  budget?: string | null;
  mapUrl?: string | null;
  geoStatus: 'provider-enrichment-required' | 'coordinates-required' | 'verified';
  latitude?: number | null;
  longitude?: number | null;
  providerPlaceId?: string | null;
  importedDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourceTable?: string | null;
  sourceRowId?: string | null;
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'updated' | 'archived';
  seo: {
    title: string;
    description: string;
    canonicalUrl?: string | null;
    openGraphImage?: (number | null) | Media;
    robots: 'index,follow' | 'noindex,follow' | 'noindex,nofollow';
    schemaType: string;
  };
  sources?:
    | {
        label: string;
        url: string;
        type: 'official' | 'map-provider' | 'editorial' | 'partner' | 'user-submitted';
        verifiedAt: string;
        confidence: 'low' | 'medium' | 'high';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts".
 */
export interface District {
  id: number;
  name: string;
  slug: string;
  city: number | City;
  zone: 'central' | 'north' | 'south' | 'east' | 'west' | 'airport' | 'coastal' | 'suburban';
  summary: string;
  latitude: number;
  longitude: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  geo: [number, number];
  mapUrl: string;
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'updated' | 'archived';
  sources?:
    | {
        label: string;
        url: string;
        type: 'official' | 'map-provider' | 'editorial' | 'partner' | 'user-submitted';
        verifiedAt: string;
        confidence: 'low' | 'medium' | 'high';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighborhoods".
 */
export interface Neighborhood {
  id: number;
  name: string;
  slug: string;
  city: number | City;
  district: number | District;
  clusterType:
    | 'historic'
    | 'business'
    | 'shopping'
    | 'food'
    | 'family'
    | 'waterfront'
    | 'airport'
    | 'religious'
    | 'mixed';
  operatingGuide: string;
  bestFor?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  latitude: number;
  longitude: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  geo: [number, number];
  mapUrl: string;
  liveMapQueries:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'updated' | 'archived';
  seo: {
    title: string;
    description: string;
    canonicalUrl?: string | null;
    openGraphImage?: (number | null) | Media;
    robots: 'index,follow' | 'noindex,follow' | 'noindex,nofollow';
    schemaType: string;
  };
  sources?:
    | {
        label: string;
        url: string;
        type: 'official' | 'map-provider' | 'editorial' | 'partner' | 'user-submitted';
        verifiedAt: string;
        confidence: 'low' | 'medium' | 'high';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  name: string;
  slug: string;
  listingType: 'place' | 'hotel' | 'restaurant' | 'masjid' | 'shopping' | 'tour' | 'islamic-landmark' | 'prayer-area';
  city: number | City;
  neighborhood: number | Neighborhood;
  shortDescription: string;
  editorialBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  address: string;
  latitude: number;
  longitude: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  geo: [number, number];
  mapUrl: string;
  phone?: string | null;
  website?: string | null;
  openingHours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  priceRange?: string | null;
  affiliateUrl?: string | null;
  muslimTravel?: {
    isHalal?: boolean | null;
    halalCertification?: string | null;
    womenPrayerArea?: boolean | null;
    familyFriendly?: boolean | null;
    notes?: string | null;
  };
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'updated' | 'archived';
  seo: {
    title: string;
    description: string;
    canonicalUrl?: string | null;
    openGraphImage?: (number | null) | Media;
    robots: 'index,follow' | 'noindex,follow' | 'noindex,nofollow';
    schemaType: string;
  };
  sources?:
    | {
        label: string;
        url: string;
        type: 'official' | 'map-provider' | 'editorial' | 'partner' | 'user-submitted';
        verifiedAt: string;
        confidence: 'low' | 'medium' | 'high';
        id?: string | null;
      }[]
    | null;
  lastVerifiedAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itineraries".
 */
export interface Itinerary {
  id: number;
  title: string;
  slug: string;
  city: number | City;
  durationDays: number;
  audience: 'first-time' | 'family' | 'muslim-traveler' | 'business' | 'budget' | 'luxury';
  summary: string;
  days: {
    dayNumber: number;
    theme: string;
    stops?: (number | Listing)[] | null;
    routeNotes?: string | null;
    id?: string | null;
  }[];
  workflowStatus: 'draft' | 'review' | 'approved' | 'published' | 'updated' | 'archived';
  seo: {
    title: string;
    description: string;
    canonicalUrl?: string | null;
    openGraphImage?: (number | null) | Media;
    robots: 'index,follow' | 'noindex,follow' | 'noindex,nofollow';
    schemaType: string;
  };
  sources?:
    | {
        label: string;
        url: string;
        type: 'official' | 'map-provider' | 'editorial' | 'partner' | 'user-submitted';
        verifiedAt: string;
        confidence: 'low' | 'medium' | 'high';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-jobs".
 */
export interface AiJob {
  id: number;
  agent:
    | 'city-content'
    | 'seo'
    | 'data-validation'
    | 'map-enrichment'
    | 'itinerary'
    | 'muslim-travel'
    | 'content-update';
  taskType: string;
  input:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  output?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'queued' | 'running' | 'completed' | 'failed' | 'blocked';
  validationReport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "update-logs".
 */
export interface UpdateLog {
  id: number;
  entityType: string;
  entitySlug: string;
  changeType: 'created' | 'verified' | 'geo-updated' | 'seo-updated' | 'source-updated' | 'archived';
  summary: string;
  sourceSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  verifiedAt: string;
  verifiedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'countries';
        value: number | Country;
      }
    | {
        relationTo: 'cities';
        value: number | City;
      }
    | {
        relationTo: 'guide-sections';
        value: number | GuideSection;
      }
    | {
        relationTo: 'guide-items';
        value: number | GuideItem;
      }
    | {
        relationTo: 'neighborhoods';
        value: number | Neighborhood;
      }
    | {
        relationTo: 'listings';
        value: number | Listing;
      }
    | {
        relationTo: 'itineraries';
        value: number | Itinerary;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'guide-sections';
        value: number | GuideSection;
      } | null)
    | ({
        relationTo: 'guide-items';
        value: number | GuideItem;
      } | null)
    | ({
        relationTo: 'districts';
        value: number | District;
      } | null)
    | ({
        relationTo: 'neighborhoods';
        value: number | Neighborhood;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'itineraries';
        value: number | Itinerary;
      } | null)
    | ({
        relationTo: 'ai-jobs';
        value: number | AiJob;
      } | null)
    | ({
        relationTo: 'update-logs';
        value: number | UpdateLog;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  attribution?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  iso2?: T;
  iso3?: T;
  region?: T;
  subregion?: T;
  capital?: T;
  currency?: T;
  timezoneNotes?: T;
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  callingCodes?:
    | T
    | {
        code?: T;
        id?: T;
      };
  summary?: T;
  flagEmoji?: T;
  workflowStatus?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        openGraphImage?: T;
        robots?: T;
        schemaType?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        type?: T;
        verifiedAt?: T;
        confidence?: T;
        id?: T;
      };
  lastVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  region?: T;
  locale?: T;
  lede?: T;
  heroImage?: T;
  timezone?: T;
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  currency?: T;
  latitude?: T;
  longitude?: T;
  geo?: T;
  mapUrl?: T;
  fastFacts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  structuredSections?: T;
  workflowStatus?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        openGraphImage?: T;
        robots?: T;
        schemaType?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        type?: T;
        verifiedAt?: T;
        confidence?: T;
        id?: T;
      };
  lastVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-sections_select".
 */
export interface GuideSectionsSelect<T extends boolean = true> {
  title?: T;
  sectionSlug?: T;
  city?: T;
  sectionType?: T;
  summary?: T;
  body?: T;
  sourceImport?: T;
  workflowStatus?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        openGraphImage?: T;
        robots?: T;
        schemaType?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        type?: T;
        verifiedAt?: T;
        confidence?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-items_select".
 */
export interface GuideItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  city?: T;
  section?: T;
  sectionSlug?: T;
  summary?: T;
  body?: T;
  image?: T;
  imageAlt?: T;
  area?: T;
  category?: T;
  budget?: T;
  mapUrl?: T;
  geoStatus?: T;
  latitude?: T;
  longitude?: T;
  providerPlaceId?: T;
  importedDetails?: T;
  sourceTable?: T;
  sourceRowId?: T;
  workflowStatus?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        openGraphImage?: T;
        robots?: T;
        schemaType?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        type?: T;
        verifiedAt?: T;
        confidence?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts_select".
 */
export interface DistrictsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  zone?: T;
  summary?: T;
  latitude?: T;
  longitude?: T;
  geo?: T;
  mapUrl?: T;
  workflowStatus?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        type?: T;
        verifiedAt?: T;
        confidence?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighborhoods_select".
 */
export interface NeighborhoodsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  district?: T;
  clusterType?: T;
  operatingGuide?: T;
  bestFor?:
    | T
    | {
        value?: T;
        id?: T;
      };
  latitude?: T;
  longitude?: T;
  geo?: T;
  mapUrl?: T;
  liveMapQueries?: T;
  workflowStatus?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        openGraphImage?: T;
        robots?: T;
        schemaType?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        type?: T;
        verifiedAt?: T;
        confidence?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  listingType?: T;
  city?: T;
  neighborhood?: T;
  shortDescription?: T;
  editorialBody?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  geo?: T;
  mapUrl?: T;
  phone?: T;
  website?: T;
  openingHours?: T;
  priceRange?: T;
  affiliateUrl?: T;
  muslimTravel?:
    | T
    | {
        isHalal?: T;
        halalCertification?: T;
        womenPrayerArea?: T;
        familyFriendly?: T;
        notes?: T;
      };
  workflowStatus?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        openGraphImage?: T;
        robots?: T;
        schemaType?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        type?: T;
        verifiedAt?: T;
        confidence?: T;
        id?: T;
      };
  lastVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itineraries_select".
 */
export interface ItinerariesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  city?: T;
  durationDays?: T;
  audience?: T;
  summary?: T;
  days?:
    | T
    | {
        dayNumber?: T;
        theme?: T;
        stops?: T;
        routeNotes?: T;
        id?: T;
      };
  workflowStatus?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        openGraphImage?: T;
        robots?: T;
        schemaType?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        type?: T;
        verifiedAt?: T;
        confidence?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-jobs_select".
 */
export interface AiJobsSelect<T extends boolean = true> {
  agent?: T;
  taskType?: T;
  input?: T;
  output?: T;
  status?: T;
  validationReport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "update-logs_select".
 */
export interface UpdateLogsSelect<T extends boolean = true> {
  entityType?: T;
  entitySlug?: T;
  changeType?: T;
  summary?: T;
  sourceSnapshot?: T;
  verifiedAt?: T;
  verifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}